# Generated by Django 2.0.2 on 2020-08-23 15:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roomcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30)),
                ('services', ckeditor.fields.RichTextField()),
                ('roomsize', models.CharField(max_length=30)),
                ('beds', models.CharField(max_length=30)),
                ('capcity', models.CharField(max_length=30)),
                ('bedtype', models.CharField(max_length=30)),
                ('roomavailable', models.IntegerField(default=0)),
                ('Image', models.ImageField(blank='True', null='True', upload_to='pics')),
            ],
        ),
    ]
