# Generated by Django 2.0.2 on 2020-08-25 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_roomcategorydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateField()),
                ('checkoutdate', models.DateField()),
                ('amount', models.IntegerField()),
                ('totalpersons', models.IntegerField()),
                ('guestname', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('roomcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Roomcategory')),
                ('roomdetailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Roomcategorydetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
