# Generated by Django 2.0.2 on 2020-09-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
