# Generated by Django 2.0.2 on 2020-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='Image',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
